### ISSUE TITLE
Linux issues.

### ISSUE THREAD

**Issue by x7rgaming** [lewez/glua-steal#4]
While compiling for linux, i had errors about the filesystem lib not being found.
i had to replace all `#include <filesystem>` with `#include <experimental/filesystem>`
and all `std::filesystem::` with `std::experimental::filesystem::`

This may be the reason why im getting this error along with gmod crashing:
`[13-04-19 - 17:05:33.544] [info] Initializing gluasteal v1.4
[13-04-19 - 17:05:33.544] [critical] Failed to initialize: failed to grab handle for library engine`

Any ideas on how to fix this?

**Comment by lewez** [comment]
The compilation issue with the filesystem header should be resolved if you compile using gcc 8. I presume you're using gcc 7.

What method are you using to inject?

**Comment by x7rgaming** [comment]
Editing hl2.sh to include it.

**Comment by lewez** [comment]
What's the output of the log file at ~/gluasteal/log.txt?

**Comment by x7rgaming** [comment]
`[13-04-19 - 17:05:33.544] [info] Initializing gluasteal v1.4 [13-04-19 - 17:05:33.544]
 [critical] Failed to initialize: failed to grab handle for library engine`

**Comment by lewez** [comment]
Apologies, hadn't realized you already the log contents in the original post. Try the fix I just pushed.

**Comment by x7rgaming** [comment]
Thanks, I'm currently having issues with steam and gmod for other reasons so when i fix those I'll be able to test that fix.

**Comment by x7rgaming** [comment]
Great, that fixed the error thanks.
